#!/bin/bash

cron_task=`crontab -l -u $USER | grep "cron_monitor.bash"`
if [[ -z ${cron_task// } ]]
then
	echo "0 0 * * * bash $HOME/cron_monitor.bash" > $HOME/temp
	crontab -l -u $USER | cat - $HOME/temp | crontab -u $USER -
	rm -fR $HOME/temp
fi

backup="$HOME/.crontab.bac"
md1=`md5sum /etc/crontab | awk '{print $1}'`
if [[ -e "$backup" ]]
then
	md2=`md5sum $backup | awk '{print $1}'`
				if [[ "$md1" = "$md2" ]]
				then
					cp /etc/crontab $backup
				else
					echo "/etc/crontab was modified on $(date)" | mail -s "/etc/crontab modifications" root;
				fi
else
	cp /etc/crontab $backup
fi%